name: Spell checking
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  spelling:
    name: Spell checking
    permissions:
      contents: read
      pull-requests: write
      actions: read
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: check-spelling/check-spelling@v0.0.24
      with:
        extra_dictionaries:
          cspell:python/src/python/python.txt
          cspell:public-licenses/src/generated/public-licenses.txt
          cspell:filetypes/filetypes.txt
          cspell:python/src/python/python-lib.txt
