name: Update cached database

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
  schedule:
    # Runs at 00:20 UTC everyday
    - cron: '20 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NO_EXIT_CVE_NUM: 1
  nvd_api_key: ${{ secrets.NVD_API_KEY }}

permissions:
  contents: read

jobs:
  linux:
    name: Update linux cached database
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Get date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: cache
          key: Linux-cve-bin-tool-${{ steps.get-date.outputs.date }}
      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --editable .
      - name: Update database
        run: |
          [[ -e cache ]] && mkdir -p .cache && mv cache ~/.cache/cve-bin-tool
          python -m cve_bin_tool.cli test/assets/test-kerberos-5-1.15.1.out -u now
          python -m cve_bin_tool.mismatch_loader
          cp -r ~/.cache/cve-bin-tool cache

# Windows cache is currently disabled.
